server:
  port: 8089

spring:
  cloud:
    stream:
      bindings:
        output:
          destination: orgChangeTopic
          content-type: application\json
      kafka:
        binder:
          zk-nodes: localhost
          brokers: localhost